# Generated by Django 4.1 on 2022-10-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_blogs_imgblogs_imguser_delete_imgblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgblogs',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagenBlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCoder.imgblogs'),
        ),
    ]
